- name: Installing {{ item }} on macOS
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip"
    dest: ~/Library/Fonts/
    creates: ~/Library/Fonts/{{ item }}
    remote_src: true
  when: is_mac

- name: Installing {{ item }} on Linux
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip"
    dest: ~/.local/share/fonts/{{ item }}
    creates: ~/.local/share/fonts/{{ item }}/done
    remote_src: true
  notify: update font cache
  when: is_linux